/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Team;
import DAL.OwnerDal;
import DAL.TeamDal;
import classes.Team;
import DatabaseConnectivity.DatabaseConnectivity;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MUHAMMED BILAL
 */
public class Team_Update extends javax.swing.JFrame {

    /**
     * Creates new form Team_Add
     */
    DatabaseConnectivity objConnectivity;
    private Connection Connection;
    public Team_Update() {
        initComponents();
        objConnectivity=new DatabaseConnectivity();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        Teamid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Teammail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Teamname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Teamofficecontact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        teamfoundeddate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        ownerid = new javax.swing.JTextField();
        updateteam = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jlabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 255, 255));
        jlabel1.setText("Update Team");
        jPanel2.add(jlabel1);
        jlabel1.setBounds(440, 30, 250, 40);

        Teamid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamidActionPerformed(evt);
            }
        });
        jPanel2.add(Teamid);
        Teamid.setBounds(410, 150, 280, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Team Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(270, 230, 100, 22);
        jPanel2.add(Teammail);
        Teammail.setBounds(410, 280, 280, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Team ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(280, 160, 80, 22);
        jPanel2.add(Teamname);
        Teamname.setBounds(410, 220, 280, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Team Mail");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(270, 290, 90, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Office Contact");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(260, 350, 120, 30);
        jPanel2.add(Teamofficecontact);
        Teamofficecontact.setBounds(410, 350, 280, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Owner ID");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(260, 500, 90, 30);
        jPanel2.add(teamfoundeddate);
        teamfoundeddate.setBounds(410, 420, 280, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Founded Date");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(250, 430, 120, 30);

        ownerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owneridActionPerformed(evt);
            }
        });
        jPanel2.add(ownerid);
        ownerid.setBounds(410, 490, 280, 40);

        updateteam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateteam.setForeground(new java.awt.Color(255, 255, 255));
        updateteam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-update-48.png"))); // NOI18N
        updateteam.setText("Update");
        updateteam.setContentAreaFilled(false);
        updateteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateteamActionPerformed(evt);
            }
        });
        jPanel2.add(updateteam);
        updateteam.setBounds(480, 560, 150, 50);

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-back-arrow-48.png"))); // NOI18N
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(40, 50, 130, 57);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Background/nxUe1y.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1090, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TeamidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamidActionPerformed

    private void owneridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owneridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_owneridActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Team_Menu().setVisible(true);
            }
        });
    }//GEN-LAST:event_backActionPerformed

    private void updateteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateteamActionPerformed
        String id =Teamid.getText();
        String Name=Teamname.getText();
        String Mail=Teammail.getText();
        long contact=Long.parseLong(Teamofficecontact.getText());
        java.util.Date utilStartDate = teamfoundeddate.getDate();
        java.sql.Date d = new java.sql.Date(utilStartDate.getTime());
        int Owner_id=Integer.parseInt(ownerid.getText());
        Connection=objConnectivity.getConnection();
        TeamDal Teamdal=new TeamDal(Connection);
        OwnerDal ownerdal=new OwnerDal(Connection);
        boolean checkOwner=ownerdal.checkOwner_id(Owner_id);
        boolean checkTeamid=Teamdal.check_Team_id(id);
        if(checkOwner==true){
            if(checkTeamid==true){
                Team T=new Team(id, Name, Mail, contact, d, Owner_id);
                Teamdal.Update(T);
                setClear();
            }else{
                JOptionPane.showMessageDialog(this,"Sorry the Team is'nt Found! ");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Sorry Owner Not Found! ");
        }
    }//GEN-LAST:event_updateteamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Team_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Team_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Team_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Team_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Team_Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Teamid;
    private javax.swing.JTextField Teammail;
    private javax.swing.JTextField Teamname;
    private javax.swing.JTextField Teamofficecontact;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JTextField ownerid;
    private com.toedter.calendar.JDateChooser teamfoundeddate;
    private javax.swing.JButton updateteam;
    // End of variables declaration//GEN-END:variables

        void setClear(){
            Teamid.setText("");
            Teamname.setText("");
            Teammail.setText("");
            Teamofficecontact.setText("");
            teamfoundeddate.setDateFormatString("");
            ownerid.setText("");
        }
}
