/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Team;

import DAL.TeamDal;
import DatabaseConnectivity.DatabaseConnectivity;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MUHAMMED BILAL
 */
public class Team_Delete extends javax.swing.JFrame {

    /**
     * Creates new form Team_Add
     */
    DatabaseConnectivity objConnectivity;
    private Connection Connection;
    public Team_Delete() {
        initComponents();
        objConnectivity=new DatabaseConnectivity();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        TeamDelete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        option = new javax.swing.JComboBox<>();
        delete = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jlabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 255, 255));
        jlabel1.setText("Delete Team");
        jPanel2.add(jlabel1);
        jlabel1.setBounds(410, 60, 240, 40);

        TeamDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TeamDelete.setForeground(new java.awt.Color(255, 255, 255));
        TeamDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/google search.png"))); // NOI18N
        TeamDelete.setText("Search");
        TeamDelete.setContentAreaFilled(false);
        TeamDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(TeamDelete);
        TeamDelete.setBounds(450, 340, 150, 50);

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-back-arrow-48.png"))); // NOI18N
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(40, 50, 130, 57);

        option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Team ID", "Team Name" }));
        jPanel2.add(option);
        option.setBounds(420, 210, 230, 40);
        jPanel2.add(delete);
        delete.setBounds(390, 280, 280, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Background/nxUe1y.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1090, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Team_Menu().setVisible(true);
            }
        });
    }//GEN-LAST:event_backActionPerformed

    private void TeamDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamDeleteActionPerformed
        
        if(option.getSelectedItem()=="Select"){
            JOptionPane.showMessageDialog(this,"Please Select One Option! ");
        }else if(option.getSelectedItem()=="Team ID"){
            if(!(delete.getText().isEmpty())){
                String id=delete.getText();
                Connection=objConnectivity.getConnection();
                TeamDal dal=new TeamDal(Connection);
                boolean check=dal.check_Team_id(id);
                if(check==true){
                    dal.DeletebyID(id);
                    setClear();
                }else{
                    JOptionPane.showMessageDialog(this,"Sorry This Team is'nt Found in Database");
                }
            }

        }else if(option.getSelectedItem()=="Team Name"){
            if(!(delete.getText().isEmpty())){
                String Name=delete.getText();
                Connection=objConnectivity.getConnection();
                TeamDal dal=new TeamDal(Connection);
                boolean check=dal.check_Team_Name(Name);
                if(check==true){
                    dal.DeletebyName(Name);
                    setClear();
                }else{
                    JOptionPane.showMessageDialog(this,"Sorry This Team is'nt Found in Database");
                }
            }

        }
    }//GEN-LAST:event_TeamDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Team_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Team_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Team_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Team_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Team_Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TeamDelete;
    private javax.swing.JButton back;
    private javax.swing.JTextField delete;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JComboBox<String> option;
    // End of variables declaration//GEN-END:variables

        void setClear(){
            delete.setText("");
        }
}
