/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sheduler_Screens.Match_Shedule;

import DatabaseConnectivity.DatabaseConnectivity;
import Psl_Classes.Player1;
import Psl_Classes.SheduleMatch;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class View_Shedule extends javax.swing.JFrame {

    /**
     *
     */
     DatabaseConnectivity objConnectivity;
        private Connection Connection;
    public View_Shedule() {
        initComponents();
        objConnectivity=new DatabaseConnectivity();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public void View_All(){
        
    try{    
        Connection=objConnectivity.getConnection();
        String query="select Sea.seasonname,M.MatchId, M.date,M.Time,S.Name,M.MatchType,T.Name,Td.Name\n" +
                "  from MatchShedule M\n" +
                "  left join Stadium S\n" +
                "  on M.StadiumId=S.StadiumId\n" +
                "  left join \n" +
                "  TeamMatch Tm\n" +
                "  on M.MatchId=Tm.MatchId\n" +
                "  left join Team T\n" +
                "  on T.TeamId=Tm.TeamAId\n" +
                "  full join Team Td\n" +
                "  on Td.TeamId=Tm.TeamBId\n" +
                "  left join Season Sea\n" +
                "  on Sea.seasonId=Tm.seasonId ";
     PreparedStatement objStatement=Connection.prepareStatement(query);
     ResultSet objResult=objStatement.executeQuery();// ArrayList<Player1>userList=new ArrayList<Player1>();
     while(objResult.next()){
     SheduleMatch objShedule=new SheduleMatch();
     objShedule.setMatchType(objResult.getString("MatchType"));
     objShedule.setStadiumId(objResult.getString("Name"));
     objShedule.setTeamAId(objResult.getString(7));
     objShedule.setTeamBId(objResult.getString(8));
     objShedule.setTime(objResult.getString("Time"));
     objShedule.setDate(objResult.getDate("Date"));
     objShedule.setSeasonId(objResult.getString("seasonName"));
     objShedule.setMatchId(objResult.getString("MatchId"));
         //    userList.add(player);
            DefaultTableModel model;
            String[] columnsName ={" Team A" ,"Team B"," Date ","Time"," Stadium",  "Match Type","Season ","MatchId"};
            model = (DefaultTableModel) tbl_Data.getModel();
            Object[] tableLines=new Object[8];
            model.setColumnIdentifiers(columnsName);
      for(int i=0;i<1;i++)
                {
                    tableLines[0]= objShedule.getTeamAId();
                    tableLines[1]= objShedule.getTeamBId();
                    tableLines[2]= objShedule.getDate();
                    tableLines[3]= objShedule.getTime();
                    tableLines[4]= objShedule.getStadiumId();
                    tableLines[5]= objShedule.getMatchType();
                    tableLines[6]= objShedule.getSeasonId();
                    tableLines[7]= objShedule.getMatchId();
                    model.addRow(tableLines);
                } 
    }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Data = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(tbl_Data);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("View All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jButton2)
                    .addContainerGap(1195, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jButton2)
                    .addContainerGap(931, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       View_All();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Match_Shedule_Menu().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Shedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Shedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Shedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Shedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Shedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Data;
    // End of variables declaration//GEN-END:variables
}
