/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import DAL.DesignationDal;
import DAL.EmployeeDal;
import DAL.NationalityDal;
import classes.Employee;
import DatabaseConnectivity.DatabaseConnectivity;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MUHAMMED BILAL
 */
public class Employee_Update extends javax.swing.JFrame {

    /**
     * Creates new form Add_Owner
     */
    DatabaseConnectivity objConnectivity;
    private Connection Connection;
    Employee e1;
    public Employee_Update(Employee e) {
        initComponents();
        objConnectivity=new DatabaseConnectivity();
        Connection=objConnectivity.getConnection();
        DisplayNationalityCombox();
        e1=e;
        if(e1!=null){
            idlabel.setText(e1.getId());
            designationlabel.setText(e1.getDesignation());
            Employeemail.setText(e1.getMail());
            Employeedob.setDate(e1.getDate());
            NationalityDal n=new NationalityDal(Connection);
            String nName=n.getNameNationality(e1.getNationality());
            Employeenationality.setSelectedItem(nName);
            Employeepnumber.setText(String.valueOf(e1.getPhonenumber()));
            Employeecnic.setText(String.valueOf(e1.getCnic()));
            Employeename.setText(e1.getName());
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Employeename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Employeemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Employeepnumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Employeecnic = new javax.swing.JTextField();
        Employeedob = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        updateSheduler = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        Employeenationality = new javax.swing.JComboBox<>();
        idlabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        designationlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Employee");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 20, 260, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 180, 45, 22);

        Employeename.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Employeename);
        Employeename.setBounds(350, 170, 260, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 260, 41, 22);

        Employeemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Employeemail);
        Employeemail.setBounds(350, 250, 260, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 340, 80, 22);

        Employeepnumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Employeepnumber);
        Employeepnumber.setBounds(350, 330, 260, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CNIC");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 420, 41, 16);

        Employeecnic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Employeecnic);
        Employeecnic.setBounds(350, 410, 260, 40);

        Employeedob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Employeedob);
        Employeedob.setBounds(350, 490, 260, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date of Birth");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 500, 110, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nationality");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(220, 560, 90, 22);

        updateSheduler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateSheduler.setForeground(new java.awt.Color(255, 255, 255));
        updateSheduler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-update-48.png"))); // NOI18N
        updateSheduler.setText("Update");
        updateSheduler.setContentAreaFilled(false);
        updateSheduler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShedulerActionPerformed(evt);
            }
        });
        jPanel1.add(updateSheduler);
        updateSheduler.setBounds(670, 590, 140, 57);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(280, 110, 19, 22);

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-back-arrow-48.png"))); // NOI18N
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(10, 20, 130, 57);

        jPanel1.add(Employeenationality);
        Employeenationality.setBounds(350, 560, 260, 40);

        idlabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(idlabel);
        idlabel.setBounds(350, 90, 260, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Designation");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(760, 50, 92, 40);

        designationlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        designationlabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(designationlabel);
        designationlabel.setBounds(860, 50, 180, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Background/123.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1070, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_updatesearch().setVisible(true);
            }
        });
    }//GEN-LAST:event_backActionPerformed

    private void updateShedulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShedulerActionPerformed

        // get data in local variables
        if(!(Employeecnic.getText().isEmpty()&&Employeemail.getText().isEmpty()&&Employeepnumber.getText().isEmpty()&&Employeecnic.getText().isEmpty()&&Employeedob.getDate()!=null))
        {
            String name=Employeename.getText();
            String mail=Employeemail.getText();
            long phoneno=Long.parseLong(Employeepnumber.getText());
            long cnic=Long.parseLong(Employeecnic.getText());
            java.util.Date utilStartDate = Employeedob.getDate();
            java.sql.Date d = new java.sql.Date(utilStartDate.getTime());
            String Nationality=null;
            if(Employeenationality.getSelectedItem()=="Select"){
                JOptionPane.showMessageDialog(this,"Please Select one Option");
            }else{
                Connection=objConnectivity.getConnection();
                DesignationDal des=new DesignationDal(Connection);
                int getiddesignation=des.getIDby_DesignationName(e1.getDesignation());
                NationalityDal n=new NationalityDal(Connection);
                int nid=n.getIDNationality((String) Employeenationality.getSelectedItem());
                Employee e=new Employee(e1.getId(), name, mail, phoneno, cnic, d, nid,getiddesignation);
                EmployeeDal empdal=new EmployeeDal(Connection);
                empdal.Update(e);
                runPreviousFrame();
            }
        }

    }//GEN-LAST:event_updateShedulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Employee e = null;
                new Employee_Update(e).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Employeecnic;
    private com.toedter.calendar.JDateChooser Employeedob;
    private javax.swing.JTextField Employeemail;
    private javax.swing.JTextField Employeename;
    private javax.swing.JComboBox<String> Employeenationality;
    private javax.swing.JTextField Employeepnumber;
    private javax.swing.JButton back;
    private javax.swing.JLabel designationlabel;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton updateSheduler;
    // End of variables declaration//GEN-END:variables

    
    
        void setClear(){
        idlabel.setText("");
        Employeename.setText("");
        Employeemail.setText("");
        Employeepnumber.setText("");
        Employeecnic.setText("");
        Employeenationality.setSelectedIndex(0);
        designationlabel.setText("");
        } 
        void runPreviousFrame(){
            dispose();
                    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_updatesearch().setVisible(true);
            }
        });
        }
        void DisplayNationalityCombox(){
            NationalityDal n=new  NationalityDal(Connection=objConnectivity.getConnection());
            Employeenationality.addItem("-Select-");
            if(n.Combox()!=null){
                int i=0;
                while(i<n.Combox().size()){
                    Employeenationality.addItem(n.Combox().get(i));
                    i++;
                }
            }
    }
        
}
