/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import DAL.DesignationDal;
import DAL.EmployeeDal;
import DAL.NationalityDal;
import DatabaseConnectivity.DatabaseConnectivity;
import java.sql.Connection;
import classes.Employee;
import classes.Nationality;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author MUHAMMED BILAL
 */
public class Employee_SearchProfile extends javax.swing.JFrame {

    /**
     * Creates new form Add_Owner
     */
    Employee e1;
    private Connection connection;
    private DatabaseConnectivity objconnectivity;
    public Employee_SearchProfile(Employee e) {
        initComponents();
        objconnectivity=new DatabaseConnectivity();
        e1=e;
        if(e1!=null){
            designationemployee.setText(e1.getDesignation());
            employeeid.setText(e1.getId());
            employeefname.setText(e1.getName());
            employeemail.setText(e1.getMail());
            employeepnumber.setText(String.valueOf(e1.getPhonenumber()));
            employeecnic.setText(String.valueOf(e1.getCnic()));
            employeedob.setDate(e1.getDate());
            connection=objconnectivity.getConnection();
            NationalityDal n=new NationalityDal(connection);
            String nName=n.getNameNationality(e1.getNationality());
            employeenationality.setText(nName);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        employeefname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        employeemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        employeepnumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        employeecnic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        employeeid = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        employeedob = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        designationemployee = new javax.swing.JLabel();
        employeenationality = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 10, 230, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 240, 45, 22);

        employeefname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(employeefname);
        employeefname.setBounds(370, 230, 260, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 320, 41, 16);

        employeemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(employeemail);
        employeemail.setBounds(370, 310, 260, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 390, 80, 22);

        employeepnumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(employeepnumber);
        employeepnumber.setBounds(370, 380, 260, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CNIC");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 470, 41, 16);

        employeecnic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(employeecnic);
        employeecnic.setBounds(370, 450, 260, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date of Birth");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 530, 110, 16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nationality");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 610, 90, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(280, 160, 19, 22);

        employeeid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeidActionPerformed(evt);
            }
        });
        jPanel1.add(employeeid);
        employeeid.setBounds(370, 150, 260, 40);

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-back-arrow-48.png"))); // NOI18N
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(10, 20, 130, 57);
        jPanel1.add(employeedob);
        employeedob.setBounds(370, 530, 260, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Designation");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 90, 110, 22);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-user-100.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(800, 80, 110, 130);

        designationemployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        designationemployee.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(designationemployee);
        designationemployee.setBounds(370, 80, 260, 40);

        employeenationality.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeenationality.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(employeenationality);
        employeenationality.setBounds(370, 600, 260, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Background/123.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1070, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeidActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Search().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_SearchProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_SearchProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_SearchProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_SearchProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Employee e;
                e=null;
                new Employee_SearchProfile(e).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel designationemployee;
    private javax.swing.JTextField employeecnic;
    private com.toedter.calendar.JDateChooser employeedob;
    private javax.swing.JTextField employeefname;
    private javax.swing.JTextField employeeid;
    private javax.swing.JTextField employeemail;
    private javax.swing.JLabel employeenationality;
    private javax.swing.JTextField employeepnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
