/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;
import CreateAccount.CreateAccount_Search;
import LoginForm.LoginForm;
import Employee.Employee_Menu;
import Owner.Owner_Menu;
import Team.Team_Menu;
/**
 *
 * @author MUHAMMED BILAL
 */
public class Admin_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Menu
     */
    public Admin_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        team = new javax.swing.JButton();
        matchofficial = new javax.swing.JButton();
        owner = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Admin Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 50, 200, 40);

        team.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        team.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-cricketer-30.png"))); // NOI18N
        team.setText("Team");
        team.setBorderPainted(false);
        team.setContentAreaFilled(false);
        team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamActionPerformed(evt);
            }
        });
        jPanel1.add(team);
        team.setBounds(290, 190, 110, 39);

        matchofficial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matchofficial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-administrator-male-48.png"))); // NOI18N
        matchofficial.setText("Employee");
        matchofficial.setBorderPainted(false);
        matchofficial.setContentAreaFilled(false);
        matchofficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchofficialActionPerformed(evt);
            }
        });
        jPanel1.add(matchofficial);
        matchofficial.setBounds(370, 290, 200, 50);

        owner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        owner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-manager-48.png"))); // NOI18N
        owner.setText("Owner");
        owner.setBorderPainted(false);
        owner.setContentAreaFilled(false);
        owner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });
        jPanel1.add(owner);
        owner.setBounds(550, 190, 140, 50);

        logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-logout-rounded-up-26.png"))); // NOI18N
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(860, 40, 120, 35);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("LogOut");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(880, 90, 80, 20);

        create.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-account-50.png"))); // NOI18N
        create.setText("Create Account");
        create.setContentAreaFilled(false);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel1.add(create);
        create.setBounds(10, 480, 240, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Background/menu (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1010, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamActionPerformed
        dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Team_Menu().setVisible(true);
            }
        });
    }//GEN-LAST:event_teamActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }//GEN-LAST:event_logoutActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner_Menu().setVisible(true);
            }
        });
    }//GEN-LAST:event_ownerActionPerformed

    private void matchofficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchofficialActionPerformed
        dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Menu().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_matchofficialActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount_Search().setVisible(true);
            }
        });
    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton matchofficial;
    private javax.swing.JButton owner;
    private javax.swing.JButton team;
    // End of variables declaration//GEN-END:variables
}
